# Dependencies
gems:                [jekyll-paginate]

# Permalinks
permalink:           pretty

# Setup
title:               Jacob Millward
tagline:             "My personal internet resting place"
description:         "Home of Jacob Millward's all-natural free-range blog."
url:                 http://jacob.millward.io
baseurl:             /
paginate:            5
paginate_path:       "page:num"

github_url:         http://github.com/jacobmillward
twitter_url:        http://twitter.com/jacobmillward
